config/routes.rb
Rails.application.routes.draw do
  get 'cooperation/index'

  resources :messages
  get 'about/index'

  get 'delivery/index'

  get 'contact/index'

  get 'connect/index'
  
  get '/page/:id', to: 'articles#show'
  
  resources :portfolios
  resources :photos
  get 'welcome/index'

  resources :articles
  resources :tags
  resources :catalogs
  resources :products
  resources :groups
  resources :contents
  resources :galleries
  
  mount Rich::Engine => '/rich', :as => 'rich'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  dragonfly_accessor :image
  
  rails_admin do
    include_all_fields

    exclude_fields  :sort, :updated_at, :created_at

    edit do
      field :description, :rich_editor do
        config({
          :insert_many => true
        })
      end
    end
  end
end

app/models/catalog.rb
class Catalog < ActiveRecord::Base
  belongs_to :group
  has_many :products
  has_one :portfolio
  dragonfly_accessor :image
  
  rails_admin do
    include_all_fields
    
    exclude_fields  :sort, :updated_at, :created_at, :slave, :review, :url, :portfolio
    
    edit do
      field :description, :rich_editor do
        config({
          :insert_many => true
        })
      end
    end
  end
end

app/models/content.rb
class Content < ActiveRecord::Base
  dragonfly_accessor :image
  rails_admin do
    include_all_fields
    exclude_fields  :sort, :updated_at, :created_at
  end
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  dragonfly_accessor :image
end

app/models/group.rb
class Group < ActiveRecord::Base
  dragonfly_accessor :image
  has_many :catalogs
  has_many :products, through: :catalogs

  rails_admin do
    include_all_fields
    exclude_fields  :sort, :updated_at, :created_at, :description, :slave, :image, :url
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  dragonfly_accessor :image
  belongs_to :product
  rails_admin do
    include_all_fields
    exclude_fields  :portfolio_id, :sort, :updated_at, :created_at, :description, :slave, :url
  end
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  dragonfly_accessor :image
  belongs_to :catalog
  has_many :photos
  accepts_nested_attributes_for :photos, allow_destroy: true, reject_if: lambda {|attributes| attributes['image'].blank?}
  rails_admin do
    include_all_fields
    exclude_fields  :sort, :updated_at, :created_at, :description, :slave, :url
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  dragonfly_accessor :image
  belongs_to :catalog
  has_many :photos
  belongs_to :tag
  accepts_nested_attributes_for :photos, allow_destroy: true, reject_if: lambda {|attributes| attributes['image'].blank?}

  rails_admin do
    include_all_fields
  
    exclude_fields  :sort, :updated_at, :created_at, :slave, :review, :url
  
    edit do
      field :description, :rich_editor do
        config({
          :insert_many => true
        })
      end
      field :specification, :rich_editor do
        config({
          :insert_many => true
        })
      end
    end
    create do
      configure :description do
        default_value do
          '<p>Для уточнения подробного описание продукта обращайтесь <a href="/contact/index">по номеру телефона, либо форме обратной связи</a></p>
          <div class="price">
            <p>Цена: <span>0</span> <i class="fa fa-rub" aria-hidden="true"></i></p>
          </div>
          <div class="available">
            <ul>
              <li><span>Материал:</span> &nbsp; железо</li>
              <li><span>Вес:</span>&nbsp; 0 кг</li>
              <li><span>Доступно на складе:</span>&nbsp; под заказ</li>
            </ul>
          </div>'
        end
      end
      configure :specification do
        default_value do
          '<ul class="specification-ul">
            <li><span class="specification-heading">Материал</span> <i>|</i> <span> Метал </span>
            <div class="clear"></div>
            </li>
            <li><span class="specification-heading">Габариты </span> <i>|</i> <span>-/-/-</span>
            <div class="clear"></div>
            </li>
            <li><span class="specification-heading">Вес (kg)</span> <i>|</i> <span>0</span>
            <div class="clear"></div>
            </li>
          </ul>'
        end
      end
    end
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :products
  
  rails_admin do
    include_all_fields
    exclude_fields  :sort, :url, :slave, :image_uid, :image_name, :updated_at, :created_at
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :slave, :image_uid, :image_name, :url, :sort)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/helpers/connect_helper.rb
module ConnectHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/delivery_helper.rb
module DeliveryHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/products/show.html.erb
        <div class="main">
          <div class="wrap">
            <div class="preview-page">
              <div class="section group">
                <div class="cont-desc span_1_of_2">
                  <ul class="back-links">
                    <li><a href="/">КАТАЛОГ</a> ::</li>
                    <li><%= @product.catalog.title%> ::</li>
                    <li><%= @product.title%></li>
                    <div class="clear"> </div>
                  </ul>
                  <div class="product-details"> 
                    <div class="grid images_3_of_2">
                      <ul id="etalage">
                        <% @product.photos.each do |photo| %>
                        <% if photo.image_stored? %>
                        <li>
                        <%= image_tag photo.image.url, alt: photo.title, class: "etalage_thumb_image" %>
                        <%= image_tag photo.image.url, alt: photo.title, class: "etalage_source_image" %>
                        </li>
                        <%end%>
                        <%end%>
                      </ul>
                    </div>
                    <div class="desc span_3_of_2">
                      <h2><%= @product.title %></h2>
                      <%= @product.description.html_safe%>
                      <div class="share-desc">
                        <div class="share">
                          <!--
                            <p>Number of units :</p><input type="number" class="text_box" type="text" value="1" min="1" />        
                          -->
                        </div>
                        <div class="button"><span><a href="/contact/index">Заказать товар</a></span></div>          
                        <div class="clear"></div>
                      </div>
                      <div class="wish-list">
                        <ul>
                          <li class="wish"><a href="/delivery/index">Подробности доставки</a></li>
                        </ul>
                      </div>
                      <div class="colors-share">
                        <!-- Colors
                        <div class="color-types">
                          <h4>Available Colors</h4>
                          <form class="checkbox-buttons">
                            <ul>
                              <li><input id="r1" name="r1" type="radio"><label for="r1" class="grey"> </label></li>
                              <li><input id="r2" name="r1" type="radio"><label for="r2" class="blue"> </label></li>
                              <li><input id="r3" name="r1" type="radio"><label class="white" for="r3"> </label></li>
                              <li><input id="r4" name="r1" type="radio"><label class="black" for="r4"> </label></li>
                            </ul>
                          </form>
                        </div>
                        -->
                        <div class="social-share">
                          <h4>Публиковать в:</h4>
                          <a href="http://vk.com/share.php?url=http://metalomaster.ru/products/<%=@product.id%>" target="_blank"><i class="fa fa-vk" aria-hidden="true"></i></a>
                          <a href="http://www.odnoklassniki.ru/dk?st.cmd=addShare&amp;st.s=1&amp;st._surl=http://metalomaster.ru/products/<%=@product.id%>" target="_blank"><i class="fa fa-odnoklassniki-square" aria-hidden="true"></i></a>
                          <a href="http://www.facebook.com/sharer.php?u=http://metalomaster.ru/products/<%=@product.id%>" target="_blank"><i class="fa fa-facebook-official" aria-hidden="true"></i></a>
                        </div>
                        <div class="clear"></div>
                      </div>
                    </div>
                    <div class="clear"></div>
                  </div>
                  <div class="product_desc">  
                    <div id="horizontalTab">
                      <ul class="resp-tabs-list">
                        <li>Спецификация</li>
                        <li>Теги продукта</li>
                        <li>Оставить отзыв</li>
                        <div class="clear"></div>
                      </ul>
                      <div class="resp-tabs-container">
                        <div class="product-specifications">
                        <%= @product.specification.html_safe %>
                        </div>

                        <div class="product-tags">
                          <p>По приведенному списку тегов можно найти товар в общем каталоге нашего интернет магазина</p>
                          <h4>Теги для поиска:</h4>
                          <div class="input-box">
                          <input type="text" value="<%=@product.tag.description if @product.tag %>" disabled>
                        </div>
                        <div class="button"><span><a href="#">Поиск тегов</a></span></div>
                      </div>  

                      <div class="review">
                        <div class="your-review"><h4>Оцените продукт</h4></div>
                        <p>В данном месте Вы можете оставить свой отзыв. Напишите объективную оценку приобретенному продукту. Оцените качество обслуживания оператора магазина. Расскажите о имеющихся проблемах. Перечислите оп возможности плюсы товара. Благодаря вашим отзывам мы стараемся делать наши продукты и оказываемые услуги на более высоком уровне</p>
                        <div class="your-review">
                          <h4>Как вы оцениваете продукт</h4>
                          <p>Напишите ваш отзыв</p>
                          <form>
                            <div>
                              <span><label>Как к вам обращаться<span class="red">*</span></label></span>
                              <span><input type="text" value=""></span>
                            </div>
                            <div><span><label>Общая оценка<span class="red">*</span></label></span>
                              <span><input type="text" value=""></span>
                            </div>            
                            <div>
                              <span><label>Отзыв<span class="red">*</span></label></span>
                              <span><textarea> </textarea></span>
                            </div>
                            <div>
                              <span><input type="submit" value="ОТПРАВИТЬ ОТЗЫВ"></span>
                            </div>
                          </form>
                        </div>      
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="rightsidebar span_3_of_1 sidebar">
                <% if @products_popular.size >= 1%>
                <h3>Популярные товары</h3>
                <ul class="popular-products">
                  <%@products_popular.each do |product|%>
                  <li>
                    <h4><a href="preview.html"><%product.title%></a></h4>
                    <%= link_to product_path do %>
                      <%=image_tag product.image.url, alt: product.title %>
                    <%end%>
                    <div class="price-details">
                      <div class="price-number">
                        <p><span class="rupees line-through"><%=product.price_old%> <i class="fa fa-rub" aria-hidden="true"></i></span> &nbsp; <span class="rupees"><%=product.price_new%> <i class="fa fa-rub" aria-hidden="true"></i></span></p>
                      </div>
                      <div class="add-cart">                
                        <h4><a href="/products/<%=product.id%>">Подробнее</a></h4>
                      </div>
                      <div class="clear"></div>
                    </div>           
                  </li>
                  <%end%>
                </ul>
                <%end%>

                <div class="community-poll">
                  <h3>Опрос магазина</h3>
                  <p>Чтобы вы хотели видеть на сайте?</p>
                  <div class="poll">
                    <form>
                      <ul>
                        <li>
                          <input type="radio" name="vote" class="radio" value="1">
                          <span class="label"><label>Больше фото</label></span>
                        </li>
                        <li>
                          <input type="radio" name="vote" class="radio" value="2">
                          <span class="label"><label for="vote_2">Сниженные цены</label></span>
                        </li>
                        <li>
                          <input type="radio" name="vote" class="radio" value="3">
                          <span class="label"><label for="vote_3">Расширенный ассортимент</label></span>
                        </li>
                        <li>
                          <input type="radio" name="vote" class="radio" value="5">
                          <span class="label"><label for="vote_5">Способы оплаты</label></span>
                        </li>
                        <li>
                          <input type="radio" name="vote" class="radio" value="6">
                          <span class="label"><label for="vote_6">Информация о гарантии</label></span>
                        </li>
                      </ul>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="content_top">
          <%= render 'shared/content_top' %>
        </div>
      </div>
      <%= javascript_include_tag 'star-rating.js', 'data-turbolinks-track' => true %>
      <script type="text/javascript">
        $(document).on('turbolinks:load', function () {
          $('#horizontalTab').easyResponsiveTabs({
            type: 'default', //Types: default, vertical, accordion           
            width: 'auto', //auto or any width like 600px
            fit: true   // 100% fit in a container
          });
          
          $('#etalage').etalage({
            thumb_image_width: 300,
            thumb_image_height: 400,
            source_image_width: 900,
            source_image_height: 1200,
            show_hint: true,
            click_callback: function(image_anchor, instance_id){
              alert('Callback example:\nYou clicked on an image with the anchor: "'+image_anchor+'"\n(in Etalage instance: "'+instance_id+'")');
            }
          });

          /* place inside document ready function */
          $(".rating").starRating({
            minus: true // step minus button
          });

        });
      </script>